services:
  unilink_postgres:
    container_name: 'unilink-postgres'
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: unilink
      POSTGRES_PASSWORD: password
    ports:
      - '54321:5432'
